// Package cppnames mirrors a C++ topic/service name header into Go: `const
// char*` declarations become Go constants and `std::array<std::pair<...>>`
// tables become map literals, plus a MirroredNames reverse map. The header
// stays the single source of truth; the mirror only restates it so Go stops
// re-typing the strings.
//
// It is a [gogen.Emitter], enabled by the `names:` config section:
//
//	names:
//	  header: include/names.h   # the C++ header to mirror
//	  out: ros/names.g.go       # config-relative output file
//	  source: include/names.h   # optional `// source:` spelling
//	  comment: |                # optional extra doc block
//	    Rename in the header, not here.
package cppnames

import (
	"bufio"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"

	"github.com/HeoJeongBo/rosidl-gen-go/gogen"
)

// Config is the `names:` section of rosidl-gen.yaml.
type Config struct {
	// Header is the C++ header that is the single source of truth for names.
	Header string `yaml:"header"`
	// Out is the generated Go file, relative to the config file (not to the
	// core `out` directory).
	Out string `yaml:"out"`
	// Source overrides the `// source:` line of the generated file; it
	// defaults to Header as written. Use it when the configured path is not
	// the spelling you want recorded in the generated file.
	Source string `yaml:"source"`
	// Comment is an extra doc block rendered below the source line, one Go
	// comment line per input line. Empty means none.
	Comment string `yaml:"comment"`
}

// Emitter mirrors the configured header; it implements [gogen.Emitter].
type Emitter struct {
	c Config
}

// New returns an Emitter for c.
func New(c Config) *Emitter { return &Emitter{c: c} }

// FromConfig claims the `names:` section of cfg. ok is false when the config
// has no such section, in which case the emitter should not run.
func FromConfig(cfg *gogen.Config) (e *Emitter, ok bool, err error) {
	var c Config
	ok, err = cfg.Section("names", &c)
	if !ok || err != nil {
		return nil, ok, err
	}
	if c.Header == "" || c.Out == "" {
		return nil, true, fmt.Errorf("names: `header` and `out` are required")
	}
	return New(c), true, nil
}

// Name identifies the emitter in errors.
func (e *Emitter) Name() string { return "cppnames" }

// Emit parses the header and renders the Go mirror. It reads the two
// constructs a name header is built from: `const char*` scalars and
// `std::array<std::pair<const char*, const char*>>` tables.
func (e *Emitter) Emit(g *gogen.Generator) ([]gogen.File, error) {
	header := g.Config().Path(e.c.Header)
	b, err := os.ReadFile(header)
	if err != nil {
		return nil, err
	}

	body, err := render(g.Config().Package, string(b), e.c)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", header, err)
	}
	formatted, err := gogen.FormatFile(e.c.Out, body)
	if err != nil {
		return nil, err
	}
	return []gogen.File{{Name: e.c.Out, Body: formatted}}, nil
}

// render turns the header source into unformatted Go source.
func render(pkg, src string, c Config) ([]byte, error) {
	scalars, tables, err := parseNameHeader(src)
	if err != nil {
		return nil, err
	}
	if len(scalars) == 0 {
		return nil, fmt.Errorf("no `const char*` name declarations found")
	}

	source := c.Source
	if source == "" {
		source = c.Header
	}

	var body strings.Builder
	body.WriteString("// Code generated by rosidl-gen. DO NOT EDIT.\n")
	fmt.Fprintf(&body, "// source: %s\n", source)
	if c.Comment != "" {
		body.WriteString("//\n")
		body.WriteString(gogen.CommentBlock("", strings.Split(strings.TrimRight(c.Comment, "\n"), "\n")))
	}
	body.WriteString("\n")
	fmt.Fprintf(&body, "package %s\n\n", pkg)

	body.WriteString("const (\n")
	for _, s := range scalars {
		body.WriteString(gogen.CommentBlock("\t", s.Doc))
		fmt.Fprintf(&body, "\t%s = %q\n", goNameIdent(s.Symbol), s.Value)
	}
	body.WriteString(")\n\n")

	for _, t := range tables {
		ident := goNameIdent(t.Symbol)
		body.WriteString(gogen.CommentBlock("", t.Doc))
		fmt.Fprintf(&body, "var %s = map[string]string{\n", ident)
		for _, k := range t.Keys {
			fmt.Fprintf(&body, "\t%q: %q,\n", k, t.ByKey[k])
		}
		body.WriteString("}\n\n")
	}

	fmt.Fprintf(&body, "// MirroredNames maps every name declared by %s to the C++ symbol\n", filepath.Base(source))
	body.WriteString("// that declares it. A contract test can use it to reject ROS name literals\n")
	body.WriteString("// that bypass the header.\n")
	body.WriteString("var MirroredNames = map[string]string{\n")
	seen := map[string]string{}
	for _, s := range scalars {
		if _, dup := seen[s.Value]; !dup {
			seen[s.Value] = s.Symbol
		}
	}
	for _, t := range tables {
		for _, k := range t.Keys {
			if _, dup := seen[t.ByKey[k]]; !dup {
				seen[t.ByKey[k]] = t.Symbol + "[" + k + "]"
			}
		}
	}
	for _, v := range slices.Sorted(maps.Keys(seen)) {
		fmt.Fprintf(&body, "\t%q: %q,\n", v, seen[v])
	}
	body.WriteString("}\n")

	return []byte(body.String()), nil
}

var (
	// inline constexpr const char* kFoo = "value";
	scalarRe = regexp.MustCompile(`const char\*\s+(\w+)\s*=\s*"([^"]*)";`)
	// inline constexpr std::array<...> kFoo = {{ {"k", "v"}, ... }};
	arrayHeadRe = regexp.MustCompile(`std::array<.*?>\s+(\w+)\s*=\s*\{\{`)
	// The declared element count, used to reject a table that parsed short.
	arraySizeRe = regexp.MustCompile(`std::array<.*,\s*(\d+)>`)
	// A table value is either a string literal or a reference to a scalar
	// declared elsewhere in the header (`{"default", kResetAllService}`).
	// Matching only the literal spelling drops such an entry SILENTLY, which
	// costs a whole endpoint: the name vanishes from the generated map without
	// a word. Groups: key, literal value, symbol value.
	pairRe = regexp.MustCompile(`\{\s*"([^"]*)"\s*,\s*(?:"([^"]*)"|(\w+))\s*\}`)
	// Section rules — a run of dashes or box-drawing characters, with or
	// without a label in the middle — are layout, not documentation. A bare
	// all-dashes test is not enough: a labelled rule contains letters, so it
	// would otherwise be captured as the doc comment of whatever declaration
	// follows it.
	sectionRe = regexp.MustCompile(`^[\s\p{Pd}\x{2500}-\x{257F}]*$|[\p{Pd}\x{2500}-\x{257F}]{3,}`)
)

// nameScalar is one `const char*` entry of the header.
type nameScalar struct {
	Symbol string
	Value  string
	Doc    []string
}

// nameTable is one `std::array<std::pair<...>>` entry of the header.
type nameTable struct {
	Symbol string
	Doc    []string
	// Keys preserves header order so the generated map literal is stable.
	Keys  []string
	ByKey map[string]string
	// symRefs holds entries whose value is another symbol in the header; they
	// are resolved after the whole file is scanned, so the referenced scalar
	// may be declared after the table.
	symRefs map[string]string
}

func parseNameHeader(src string) ([]nameScalar, []nameTable, error) {
	var (
		scalars []nameScalar
		tables  []nameTable
		pending []string
	)

	sc := bufio.NewScanner(strings.NewReader(src))
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)

		switch {
		case trimmed == "":
			pending = nil
			continue
		case strings.HasPrefix(trimmed, "///"):
			continue // namespace doc block
		case strings.HasPrefix(trimmed, "//"):
			text := strings.TrimSpace(strings.TrimPrefix(trimmed, "//"))
			if !sectionRe.MatchString(text) {
				pending = append(pending, text)
			}
			continue
		}

		if m := scalarRe.FindStringSubmatch(line); m != nil {
			scalars = append(scalars, nameScalar{Symbol: m[1], Value: m[2], Doc: pending})
			pending = nil
			continue
		}

		if m := arrayHeadRe.FindStringSubmatch(line); m != nil {
			t := nameTable{
				Symbol:  m[1],
				Doc:     pending,
				ByKey:   map[string]string{},
				symRefs: map[string]string{},
			}
			pending = nil

			block := line
			for !strings.Contains(block, "}};") {
				if !sc.Scan() {
					return nil, nil, fmt.Errorf("unterminated std::array for %s", t.Symbol)
				}
				block += "\n" + sc.Text()
			}
			for _, p := range pairRe.FindAllStringSubmatch(block, -1) {
				key, lit, sym := p[1], p[2], p[3]
				if slices.Contains(t.Keys, key) {
					return nil, nil, fmt.Errorf("%s declares key %q twice", t.Symbol, key)
				}
				t.Keys = append(t.Keys, key)
				if sym != "" {
					t.symRefs[key] = sym
					continue
				}
				t.ByKey[key] = lit
			}
			if len(t.Keys) == 0 {
				return nil, nil, fmt.Errorf("%s declares no entries", t.Symbol)
			}
			// The declared size is the only thing that catches an entry this
			// parser cannot read: without it a missed spelling just yields a
			// shorter map, and the name it held disappears without a word.
			// A size this regexp cannot read (a named constant, say) would
			// disable that guard just as silently, so it is an error too.
			s := arraySizeRe.FindStringSubmatch(block)
			if s == nil {
				return nil, nil, fmt.Errorf(
					"%s: cannot read the declared std::array size; spell it as a literal so short parses stay detectable",
					t.Symbol)
			}
			want, err := strconv.Atoi(s[1])
			if err != nil {
				return nil, nil, fmt.Errorf("%s: declared std::array size: %w", t.Symbol, err)
			}
			if want != len(t.Keys) {
				return nil, nil, fmt.Errorf(
					"%s declares %d entries but %d parsed; an entry uses a spelling this parser does not read",
					t.Symbol, want, len(t.Keys))
			}
			tables = append(tables, t)
			continue
		}

		pending = nil
	}
	if err := sc.Err(); err != nil {
		return nil, nil, err
	}

	// arrayHeadRe needs the whole `std::array<…> kFoo = {{` on ONE line; a
	// formatter that wraps it makes the table vanish entirely — not short, so
	// the size check above never runs. Counting declarations catches that.
	if declared := strings.Count(src, "std::array<"); declared != len(tables) {
		return nil, nil, fmt.Errorf(
			"%d std::array declarations but %d tables parsed; a declaration is probably wrapped across lines",
			declared, len(tables))
	}

	// Resolve `{"key", kSomeSymbol}` entries now that every scalar is known.
	byScalar := make(map[string]string, len(scalars))
	for _, s := range scalars {
		byScalar[s.Symbol] = s.Value
	}
	for i := range tables {
		for key, sym := range tables[i].symRefs {
			v, ok := byScalar[sym]
			if !ok {
				return nil, nil, fmt.Errorf("%s[%q] references %s, which the header does not declare",
					tables[i].Symbol, key, sym)
			}
			tables[i].ByKey[key] = v
		}
	}

	slices.SortFunc(scalars, func(a, b nameScalar) int { return strings.Compare(a.Symbol, b.Symbol) })
	slices.SortFunc(tables, func(a, b nameTable) int { return strings.Compare(a.Symbol, b.Symbol) })
	return scalars, tables, nil
}

// goNameIdent drops the C++ `k` constant prefix: kCmdTopic -> CmdTopic.
func goNameIdent(symbol string) string {
	if len(symbol) > 1 && symbol[0] == 'k' && symbol[1] >= 'A' && symbol[1] <= 'Z' {
		return symbol[1:]
	}
	return symbol
}
